name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        docker run -d --name my-app2 -p8000:80 my-image-name:$(date +%s)
        docker tag my-image-name:$(date +%s) 00010009/deploy-website
        docker push 00010009/deploy-website
